apiVersion: v2
name: backend
description: Cuddly-disco backend Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - backend
  - python
  - flask
  - api
maintainers:
  - name: cuddly-disco
