apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
