apiVersion: v2
name: frontend
description: Cuddly-disco frontend Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - frontend
  - react
  - vite
  - nginx
maintainers:
  - name: cuddly-disco
